dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
slack:
rooms:
  secure: "JVi1z2JJ8g8qbRfleC4qm//r3BbUXOeMsQbn245wmuQk/g0atkV5jaZKgjCtinao6habD4XhIvlaKhbB73VBJdJ+LsJO9aFmE7jy7AqxuifUODAN3We8iG68eri05J0UpkuXVog6uop04VsMlW+fCw/ewCs4/sFy5TY5Une8Q67/Ru+FhEICBdPDNj+opAvUjvx71uYKsOFv6YqTyps3QuS49w4kmrfe0SsGQcN8sUnvv2RUx3/vIYbJ7k2ML2TMLXooHhMoo0/+DSEUdqxWhwnTMeSDYw7tcpmKDIPQeNt0mqAVYpVlPEOHvJ99RkajZux7+EsDRtEAjuuUnyQMJXf+UPhC06mgwfqjAifMiScMJlKyXjLAdVYmM5wl9kG/6ivEwiHNefTDo/ghkWrrWSEdsIrsUPTGXpSilxLcwZdEeshTYdWEZInR/EQ8U4Yz7NFq+YTt9ChZrjNmwHfOD0CPUp/I/NAS5MixAFqt4GN6xTcIwqjq5B+9xXQU0RBCz7cbn/QW6IX94MhQOgHqxzAhjz0ePK46MxlaMsCF2QgVvU1cGnVt1hIy+Xe9wpmNPwM8YEHuBNlZIPfNzKVWC8ahvF1cpr3u5XxgGzeEygPr/oqfYHufGepLO6KUfgZsn5U4WLakFsHyPSXVdEkgXIjnBT4DbfK69IhIMVo6CJk="

