dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
slack:
rooms:
  secure:
Q25PPv4u17biNNbwMaKr/o6aLprAAYq4ZGRw11jnQi1ee6NX58B8EMHZGFE4WbZnaNIEXFDajVZI2q4fZW9pQHohrSK+5JAZ1IkcxE3v2KEFM6O2znoaicvjI/4Q0G0zY6RxSHaM1zRcltpPQY6FJ99zuPkVP1ZLGxVYNka+pFlTYAXPr0gbywwopDIKU9Mt1Qm43XM9jsJ8yg8WEg31H0faFBLsSLY1GSS9mwgzAqHKA91d6ESaBZbb8i2xq4LfrTz/I2R62SqCgtu2QCgFdRaxcc7yz5fCpLjKPokN9zS51nl/MrEG3pbpQOcwbx4yxAQXFYNcQJ6IXcpEJ7gvauYR26xR0cx3XeFDXCdPwIH47VIt8vpOntK/CkCQg8VHI2Z/DeiRqt/38sOG8jW6f3BB8ET/epq15MHr9yN/nnER69/4my5XMemBowFjRIWJyT3hicyVxRuCOgHR66u3RURQbin903k0E1g/eZLCsBn8W5u1bRifyCVDzkSE7YKcUPsWPbt5uBdt2cOJAOPKJNjwycl4eZZ1NQfe3W722B8ZHx58Klg25rbHJqaHwsFcoTA5L9wUf5ht/Mj9Z4FGju792mG8fhIUv0u+FJnJ5FHprVfFbkd6NkcURd4Za5zwvMAW2LU1SPfr2qEQlKHxjaTsr8hr9TwWRqt4Ihsq8bE=
          
