dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
slack:
rooms:
secure:
XzevYDfsY0huZyKfvUaMwV/FzIWxklt43SIcEB6vQBCzr/fGvIJLoYPE2gUvDalasDFrWmZMQhJ7BvS3baESfSk1b6geXV8j8aOImPk+DCgeHxUDoh2qUIYQX7Te1p02HjsW+deQOU9fMq4JudUODs0WOQ2y5yVC9qmeJNj1+duIMjMrMCHjtAymfUID9UDHLpWXGC3g2nt4TrAc7zxwgoDqkYYeiLriouHdOhDyeDlp9Aq/8Zyl+mfW7DHGtlNKLtsMax5K631U2a6Cop7IR4dfoxD2QRPihvxNDMRnj4EZSeZGMLEVNUKywCe2GViKGpc2kr0lmG94oXcaaK5VaF5jFoX3ap05FiJUTAk8zae0eEdNgazRKq8EeyuiRviY4wtQoMRmNGCd5WMRhuvgro5P+LK958D+tDajhuMSSaezDHg4pQ0Qr5jRzHhGTmxvQczkt23jStPkmGdlEIv044I/I+JcNGf0x5UOTWiMke+0dddhxTydOoIfmlPZjDXpcPDXQ4DrVQJ8v+ZIMcqllUBrQof7/oZlfOykdx7bpw31UnbdG04aR6d3akNmTcABz/IuHez45t7h9jkDoMYmpEq97wLA+CnFc5LA1j8MHprmr5Eh9jPZySiD+7MRLGtzbivwoLjpw/Qbjr74vFli0dlQT+CRd5ltJjw/q13fFME="

